export const packets = [
  {
    id: 1,
    name: "Nasi Goreng Spesial + Teh Manis Dingin",
    price: 19000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 2,
    name: "Nasi Goreng Spesial + Tropical Punch",
    price: 25000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 3,
    name: "Nasi Goreng Spesial + Matcha Vanilla",
    price: 25000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 4,
    name: "Indomie Goreng Spesial + Teh Manis Dingin",
    price: 17000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 5,
    name: "Indomie Goreng Spesial + Tropical Punch",
    price: 22000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 6,
    name: "Indomie Goreng Spesial + Matcha Vanilla",
    price: 22000,
    quantity: 0,
    totalPrice: 0,
  },
];

export const foods = [
  {
    id: 1,
    name: "Nasi Goreng",
    price: 12000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 2,
    name: "Nasi Goreng Spesial",
    price: 15000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 3,
    name: "Indomie Goreng",
    price: 10000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 4,
    name: "Indomie Goreng Spesial",
    price: 13000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 5,
    name: "Indomie Kuah",
    price: 10000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 6,
    name: "Indomie Kuah Spesial",
    price: 13000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 7,
    name: "Roket",
    price: 8000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 8,
    name: "Roket Jumbo",
    price: 15000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 9,
    name: "Kentang Goreng",
    price: 10000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 10,
    name: "Kentang Goreng Jumbo",
    price: 13000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 11,
    name: "Terong Crispy",
    price: 7000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 12,
    name: "Terong Crispy Jumbo",
    price: 12000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 13,
    name: "Kol Crispy",
    price: 7000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 14,
    name: "Kol Crispy Jumbo",
    price: 12000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 15,
    name: "puding telur",
    price: 6000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 16,
    name: "puding telur Jumbo",
    price: 9000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 17,
    name: "Pop mie",
    price: 7000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 18,
    name: "Nasi Putih",
    price: 5000,
    quantity: 0,
    totalPrice: 0,
  },
];

export const drinks = [
  {
    id: 25,
    name: "Tropical Punch",
    price: 13000,
    quantity: 0,
    totalPrice: 0,
    label: "NEW",
  },
  {
    id: 26,
    name: "Matcha Vanilla",
    price: 13000,
    quantity: 0,
    totalPrice: 0,
    label: "NEW",
  },
  {
    id: 27,
    name: "Orange Soda",
    price: 13000,
    quantity: 0,
    totalPrice: 0,
    label: "NEW",
  },
  {
    id: 1,
    name: "Air Mineral",
    price: 5000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 2,
    name: "Teh Manis",
    price: 5000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 3,
    name: "Teh Manis Dingin",
    price: 7000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 4,
    name: "Kopi Hitam",
    price: 5000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 5,
    name: "Kopi Hitam Dingin",
    price: 7000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 6,
    name: "Susu",
    price: 7000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 7,
    name: "Susu Dingin",
    price: 9000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 8,
    name: "Milo",
    price: 7000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 9,
    name: "Milo Dingin",
    price: 9000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 10,
    name: "Kopi Susu",
    price: 7000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 11,
    name: "Kopi Susu Dingin",
    price: 9000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 12,
    name: "Teh Tarik",
    price: 7000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 13,
    name: "Teh Tarik Dingin",
    price: 9000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 14,
    name: "Capuccino",
    price: 7000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 15,
    name: "Capuccino Dingin",
    price: 9000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 16,
    name: "Lemon Tea",
    price: 10000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 17,
    name: "Lemon Tea Dingin",
    price: 12000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 18,
    name: "TST",
    price: 10000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 19,
    name: "TST Dingin",
    price: 12000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 20,
    name: "Fanta",
    price: 7000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 21,
    name: "Coca-Cola",
    price: 7000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 22,
    name: "Sprite",
    price: 7000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 23,
    name: "Soda Gembira",
    price: 10000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 24,
    name: "Es Kosong",
    price: 2000,
    quantity: 0,
    totalPrice: 0,
  },
  {
    id: 25,
    name: "Tropical Soda",
    price: 10000,
    quantity: 0,
    totalPrice: 0,
  },
];
